### ISSUE TITLE
Virama and mark spacing issues

### ISSUE THREAD

**Issue by davelab6** [DunwichType/Padyakke_Libre#11]
@erinmclaughlin noted that when using the "Impallari test page" on Chrome, the virama is not correctly functioning and has some spacing issues with marks:

![unnamed](https://cloud.githubusercontent.com/assets/261579/14253407/625d44ca-fa59-11e5-896c-d4980ee5704a.png)

**Comment by DunwichType** [comment]
FYI I am reading this thread But I’m keeping quiet because everybody else seems to have the conversation under control and anything I add right now will be noise.

**Comment by DunwichType** [comment]
This is fixed in 1.401
