### ISSUE TITLE
Rename Extended to Expanded

### ISSUE THREAD

**Issue by davelab6** [DunwichType/Padyakke_Libre#13]
@aoifemooney 's wide BioRhyme family is `BioRhyme Expanded` ([ref](https://github.com/aoifemooney/makingbiorhyme/tree/gh-pages/Releases/2016_05_29/TTFS)) and so I think it would be best to rename this font `PadyakkeExpandedOne-Regular.ttf`

**Comment by DunwichType** [comment]
Fixed.
