### ISSUE TITLE
aspect ratio

### ISSUE THREAD

**Issue by MayuraVerma** [DunwichType/Padyakke_Libre#2]
Hello,

This is good font for Kannada. But the overall aspect ratio of the font is bulgy. It looks like the font is pressed vertical down or too fat.

I am sorry, I am not expressing my view technically. But that is what I feel on looking at the font.

Please take views of other Kannada users as well.

Great work though.

Thanks.

**Comment by DunwichType** [comment]
Thanks for sharing your thoughts. It makes sense that Padyakke looks weird to you. Padyakke is intended to be a very wide font in a family with multiple widths and weights. I don’t think there are any light, wide Kannada fonts other than Padyakke. So when I designed Padyakke I I basically invented the proportions. I have no idea if a font like this will be useful for designers who typeset Kannada, but thin extended fonts are popular for presentations in other writing systems, so the Google fonts staff and I decided to go ahead and design it.

James Puckett

**Comment by DunwichType** [comment]
Thanks for sharing your thoughts. It makes sense that Padyakke looks weird to you. Padyakke it is intended to be a very wide font in a family with multiple widths and weights. I don’t think there are any light, wide Kannada fonts other than Padyakke. So when I designed Padyakke I I basically invented the proportions. I have no idea if a font like this will be useful for designers who typeset Kannada, but thin extended fonts are popular for presentations in other writing systems, so the Google fonts staff and I decided to go ahead and design it.

**Comment by MayuraVerma** [comment]
Wonderful. Light font is a welcome. But if it was in the right proportion it was would have been a good start. rather than starting from wide proportion. If you are planning to add regular proportion in future. It would be more useful than the wide font. 

Nonetheless. it is a good font.

**Comment by DunwichType** [comment]
Thanks again. Hopefully my client will feel the same way and commission a regular width.
