### ISSUE TITLE
Add more descriptive description to README

### ISSUE THREAD

**Issue by davelab6** [DunwichType/Padyakke_Libre#5]
Please add a paragraph or two more to the top of README that describes the design (in the 3rd person) that will be useful for www.google.com/fonts directory and similar :)

**Comment by DunwichType** [comment]
The first paragraph has been rewritten.

**Comment by davelab6** [comment]
'lachrymae' is not a word I am familiar with - I think you mean lachrymose - but I think this is unusual and unlikely to make sense to non-native english readers, so I recommend using more simple English.

**Comment by DunwichType** [comment]
Updated readme again.
